version: 2.1

orbs:
  node: circleci/node@5

jobs:
  test-node:
    # Install node dependencies and run tests
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test --passWithNoTests

  build-node:
    # Build node project
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      # Copy output to artifacts dir (only if the files exist)
      - run:
          name: Copy artifacts
          command: |
            cp -R build ~/artifacts 2>/dev/null || true
            cp -R dist ~/artifacts 2>/dev/null || true
            cp -R public ~/artifacts 2>/dev/null || true
            cp -R .output ~/artifacts 2>/dev/null || true
            cp -R .next ~/artifacts 2>/dev/null || true
            cp -R .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

  semantic-release:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Semantic Release
          command: yarn semantic-release
          environment:
            NODE_AUTH_TOKEN: $NPM_TOKEN
            GH_TOKEN: $GH_TOKEN

workflows:
  build-and-test:
    jobs:
      - test-node
      - build-node:
          requires:
            - test-node
      - semantic-release:
          requires:
            - build-node

